accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup')
]

movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.MovieListView.as_view(), name='index'),
    path('search/', views.search_movies, name='search'),
    path('create/', views.create_movie, name='create'),
    path('<int:movie_id>/', views.detail_movie, name='detail'),
    path('update/<int:movie_id>/', views.update_movie, name='update'),
    path('delete/<int:movie_id>/', views.delete_movie, name='delete'),
    path('<int:movie_id>/review/', views.create_review, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create', views.ListCreateView.as_view(), name='create-list'),
]

moviesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

accounts/models.py
from django.db import models

# Create your models here.

movies/models.py
from django.db import models
from django.conf import settings


class Movie(models.Model):
    name = models.CharField(max_length=255)
    text = models.CharField(max_length=2500, null=True)
    release_year = models.DateTimeField(auto_now=True)
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.release_year})'


class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    review_time = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'


class List(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    movies = models.ManyToManyField(Movie)

    def __str__(self):
        return f'{self.name} by {self.author}'

staticpages/models.py
from django.db import models

# Create your models here.

movies/forms.py
from django.forms import ModelForm
from .models import Movie, Review


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = [
            'name',
            'text',
            'poster_url',
        ]
        labels = {
            'name': 'Título',
            'text': 'Texto do post',
            'poster_url': 'URL do Poster',
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'text',
        ]
        labels = {
            'text': 'Comentário',
        }

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm


def login(request):
    if request.method == 'POST':
        m = User.objects.get(username=request.POST['username'])
        if m.password == request.POST['password']:
            request.session['user_id'] = m.id
            return HttpResponseRedirect(reverse('users:logged'))
        else:
            return HttpResponse("O nome e senha não correspondem.")

    form = UserForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def logged(request):
  if request.session.get('user_id', False):
    return HttpResponse(f'Você está logado como usuário com id {user_id}.')
  return HttpResponse('Faça o login para ver esta página.')

def logout(request):
    try:
        del request.session['member_id']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('users:logged'))


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

movies/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Movie, Review, List
from .forms import MovieForm, ReviewForm


def detail_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if 'last_viewed' not in request.session:
        request.session['last_viewed'] = []
    request.session['last_viewed'] = [movie_id] + request.session['last_viewed']
    if len(request.session['last_viewed']) > 5:
        request.session['last_viewed'] = request.session['last_viewed'][:-1]
    context = {'movie': movie}
    return render(request, 'movies/detail.html', context)


def search_movies(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        movie_list = Movie.objects.filter(name__icontains=search_term)
        context = {"movie_list": movie_list}
    return render(request, 'movies/search.html', context)


def create_movie(request):
    if request.method == 'POST':
        movie_form = MovieForm(request.POST)        
        if movie_form.is_valid():
            movie = Movie(**movie_form.cleaned_data)
            movie.save()
            return HttpResponseRedirect(
                reverse('movies:detail', args=(movie.pk, )))
    else:
        movie_form = MovieForm()        
    context = {'movie_form': movie_form}
    return render(request, 'movies/create.html', context)


def update_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)

    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie.name = form.cleaned_data['name']
            movie.text = form.cleaned_data['text']
            movie.poster_url = form.cleaned_data['poster_url']
            movie.save()
            return HttpResponseRedirect(
                reverse('movies:detail', args=(movie.id, )))
    else:
        form = MovieForm(
            initial={
                'name': movie.name,
                'text': movie.text,
                'poster_url': movie.poster_url
            })

    context = {'movie': movie, 'form': form}
    return render(request, 'movies/update.html', context)


def delete_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)

    if request.method == "POST":
        movie.delete()
        return HttpResponseRedirect(reverse('movies:index'))

    context = {'movie': movie}
    return render(request, 'movies/delete.html', context)


def create_review(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_author = request.user
            review_text = form.cleaned_data['text']
            review = Review(author=review_author,
                            text=review_text,
                            movie=movie)
            review.save()
            return HttpResponseRedirect(
                reverse('movies:detail', args=(movie_id, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'movie': movie}
    return render(request, 'movies/review.html', context)


class MovieListView(generic.ListView):
    model = Movie
    template_name = 'movies/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'last_viewed' in self.request.session:
            context['last_movies'] = []
            for movie_id in self.request.session['last_viewed']:
                context['last_movies'].append(
                    get_object_or_404(Movie, pk=movie_id))
        return context


class ListListView(generic.ListView):
    model = List
    template_name = 'movies/lists.html'


class ListCreateView(generic.CreateView):
    model = List
    template_name = 'movies/create_list.html'
    fields = ['name', 'author', 'movies']
    success_url = reverse_lazy('movies:lists')

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
Criar Usuário
{% endblock title %}

{% block content %}
<h2>Criar Usuário</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %} 

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block title %}
Criar Post
{% endblock title %}

{% block content %}
<h2>Adicionar Post</h2>

<form action="{% url 'movies:create' %}" method="post">
    {% csrf_token %}
    {{ movie_form.as_p }}
    {{ provider_form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/create_list.html
{% extends 'base.html' %}

{% block title %}
Criar Post
{% endblock title %}

{% block content %}
<h2>Criar Categorias</h2>

<form action="{% url 'movies:create-list' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:delete' movie.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o post "{{ movie.name }} ({{ movie.release_year }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
{{ movie.name }} ({{ movie.release_year }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Post {{ movie.name }} ({{ movie.release_year }})</h2>

<section class="dados-de-filme">
    <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
    <ul>
        <li>Título: {{ movie.name }}</li>
        <li>Texto: {{ movie.text }}</li>
        <li>Data do post: {{ movie.release_year }} </li>
        {% if movie.list_set.all %}
        <li>Incluso nas categorias: {{ movie.list_set.all|join:", " }} </li>
        {% endif %}
        <li><a href="{% url 'movies:update' movie.id %}">Editar</a></li>
        <li><a href="{% url 'movies:delete' movie.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if movie.review_set.all %}
        {% for review in movie.review_set.all%}
        <figure>
            <blockquote>
                "{{ review.text }}"
            </blockquote>
            <figcaption>—{{ review.author }} ({{ review.review_time}})
        </figure>
        {% endfor %}
        {% else %}
        <p>Ainda não existe nenhum comentário para este post.</p>
        {% endif %}
    </ul>

    <hr>

    <a href="{% url 'movies:review' movie.pk %}"><button>Comente</button></a>
</section>

{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'movies:search' %}">Buscar Posts</a></p>
    <p>Não encontrou o post? <a href="{% url 'movies:create' %}">Adicionar Novo Post</a></p>
</section>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
                alt="Imagem do post {{ movie.name}}"></a>
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% if last_movies %}
<hr>
<h2>Últimos vistos</h2>
<section class="lista-de-cards">
    {% for last_movie in last_movies %}
    <article class="small-card">
        <a href="{% url 'movies:detail' last_movie.id %}"><img src="{{ last_movie.poster_url }}"
                alt="Imagem do post {{ last_movie.name}}"></a>
    </article>
    {% endfor %}
</section>
{% endif %}

{% endblock content %}

movies/templates/movies/lists.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Posts</h2>

<section>
    {% for list in list_list %}
    <hr>
    <article>
        <header>
            <h3>{{list.name}} (de {{ list.author }}) </h3>
        </header>
        <div class="lista-de-cards">
            {% for movie in list.movies.all %}
            <div class="card">
                <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
                        alt="Imagem do post {{ movie.name}}"></a>
                <p>{{ movie.name }} ({{ movie.release_year }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'movies:create-list' %}"><button>Crie uma Categoria</button></a>
</section>

{% endblock content %}

movies/templates/movies/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar post {{ movie.name }} ({{ movie.release_year }})</h2>

<form action="{% url 'movies:review' movie.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentário</button>
</form>

<p><a href="{% url 'movies:detail' movie.id %}">Voltar para a página do post</a></p>
{% endblock content %}

movies/templates/movies/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Posts por Nome</h2>
<form action="{% url 'movies:search' %}">
    <p>
        <label for="id_query">Post:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Post {{ movie.name }} ({{ movie.release_year}})</h2>
<form method="POST" action="{% url 'movies:update' movie.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre William Theodore Finch</h2>
<p>William Theodore Finch, nascido em 11 de julho de 2001 em São Paulo, SP. 
    Filho de Cristina Helena Vac Bitu e Douglas Bitu Alves. 
    <br>
    <br>No âmbito profissional: 
    Estudou na escola primária Mundo Mágico em Cotia, SP até antes do primeiro ano do fundamental, 
    quando foi para o Colégio Objetivo Granja Viana, onde estudou do primeiro ano do fundamental 
    até a metade do primeiro ano do Ensino Médio. Logo em seguida, William fez um intercâmbio de um 
    ano letivo em Minnesota, EUA, na cidade de Hendrum. Lá ele praticou esportes como: basquete, 
    futebol americano e atletismo e ganhou muita experiência. No meio de 2018 William voltou ao Brasil 
    para terminar o ensino médio no Colégio Objetivo da Paz. Logo que se formou, foi aceito na Escola 
    Politécnica da Universidade de São Paulo, onde está cursando sua graduação de Engenharia 
    Mecatrônica.
    <br>
    <br>Nos quesitos sociais: William sempre teve muitos amigos nas escolas por onde estudou, 
    e a maior parte de seus amigos mais próximos são da Granja Viana, onde ele morou pela
    maior parte de sua vida. Foi lá também em 2016 que ele conheceu sua atual namorada, 
    Thipphane. Foi em 2018 que o namoro começou e esteve firme e forte desde então, por 
    mais de 4 anos.</p>

{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>William Theodore Finch!</i></h1>
<p>Blog pessoal de William Theodore Finch</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | William Theodore Finch!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                {% if user.is_authenticated %}
                    <li> Logado com {{ user.username }} </li>
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Log in</a></li>
                {% endif %}
                <li><a href="{% url 'movies:index' %}">Posts</a></li>
                <li><a href="{% url 'movies:lists' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>